### ISSUE TITLE
Transform's input file does not exist

### ISSUE THREAD

**Issue by nizar-khan** [nyartech/hyperpay#10]
Hello, I faced this problem after adding all the required files I did (build project) and after that I got this problem ( Transform's input file does not exist: C:\Users\nizar\AndroidStudioProjects\nibrass4\android\oppwa.mobile\oppwa.mobile-3.6.0-release.aar. (See https://issuetracker.google.com/issues/158753935) )
 I tried to do ( flutter clean ) and then I restarted the app then this problem appears ( 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform oppwa.mobile-3.6.0-release.aar (project :oppwa.mobile) to match attributes {artifactType=android-assets}.
      > Execution failed for JetifyTransform: C:\Users\nizar\AndroidStudioProjects\nibrass4\android\oppwa.mobile\oppwa.mobile-3.6.0-release.aar.
         > Transform's input file does not exist: C:\Users\nizar\AndroidStudioProjects\nibrass4\android\oppwa.mobile\oppwa.mobile-3.6.0-release.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s )

**Comment by pr-Mais** [comment]
Are you able to run the example project?
What's the gradle version in your project?

Try the following:
1. In Android Studio, go to File > Invalidate Caches/Restart
2. Go to the .gradle cache on your machine (usually found in your-user/.gradle) and delete the cache foler

**Comment by pr-Mais** [comment]
Without additional information we cannot provide help, if anyone else is going through this issue I will reopen.
