### ISSUE TITLE
redirect issue

### ISSUE THREAD

**Issue by MohamedEalbd** [nyartech/hyperpay#11]
I have problem with redirect url in Andriod and IOS because my bundle id include capital letters so redirect id include capital letters
but when change my bundle id to small letter it work done This means that the problem is in case-sensitive 
Unfortunately I can not change my bundle id because my app is already upload this app in google play and app store

**Comment by pr-Mais** [comment]
Please confirm that the fix I just merged work by importing the main branch:
```
dependencies:
  hyperpay:
    git: https://github.com/nyartech/hyperpay.git
```

**Comment by AlaaEldeenYsr** [comment]
i can't import the main branch
```
hyperpay:
    git:
      url: https://github.com/nyartech/hyperpay.git
      ref: main
```
```
Running "flutter pub get" in ya_schools_parent_app...           
Could not find a file named "pubspec.yaml" in "D:\dev\env\flutter\latest\.pub-cache\git\hyperpay-57c10845389eace2ee5d3bfa08a21520d739a35b".
pub get failed (66; Could not find a file named "pubspec.yaml" in "D:\dev\env\flutter\latest\.pub-cache\git\hyperpay-57c10845389eace2ee5d3bfa08a21520d739a35b".)
exit code 66
```

**Comment by AlaaEldeenYsr** [comment]
same issue
my app bundle id doesn't contain any capital letters 
the second step of the webview goes into infinite loading In spite of the transaction is actually confirmed from the backend server.
![image](https://user-images.githubusercontent.com/52201392/181245127-cabd875c-3fe2-43d3-a20b-9f5a2864accd.png)
