### ISSUE TITLE
im in trouble with hyperpay flutter plugin

### ISSUE THREAD

**Issue by suhaibAlbdoor** [nyartech/hyperpay#14]
[HyperpayPlugin/getCheckoutID] HttpException: 400: {"result":{"code":"200.300.404","description":"invalid or missing parameter","parameterErrors":[{"name":"entityID","value":"my test entityId","message":"is not an allowed parameter"}]},"buildNumber":"01bd52148ce2598807fd43a4d36810f974eb028e@2022-04-01 07:48:59 +0000","timestamp":"2022-04-02 12:23:45+0000","ndc":"5B57484A2A9E90A0DF85D8C86427F6F1.uat01-vm-tx04"}
there is my code:

class TestConfig implements HyperpayConfig {
  String creditcardEntityID = 'test entityId';
  String madaEntityID = '';
  Uri checkoutEndpoint = _checkoutEndpoint;
  Uri statusEndpoint = _statusEndpoint;
  PaymentMode paymentMode = PaymentMode.test;
}

Uri _checkoutEndpoint = Uri(scheme: 'https', host: _host, path: '/v1/checkouts', queryParameters: {
  'currency': 'JOD',
  'paymentType': 'DB',
});

**Comment by pr-Mais** [comment]
The error is coming from HyperPay's backend, and is indicating one of the parameters you sent in your request isn't allowed, perhaps you need to check with HyperPay support.

**Comment by suhaibAlbdoor** [comment]
> The error is coming from HyperPay's backend, and is indicating one of the parameters you sent in your request isn't allowed, perhaps you need to check with HyperPay support.

thank you for replying ,
i will check issue with hyper pay support team

**Comment by suhaibAlbdoor** [comment]
> The error is coming from HyperPay's backend, and is indicating one of the parameters you sent in your request isn't allowed, perhaps you need to check with HyperPay support.

i contacted with hyper pay support and we figured out that the problem not from backend side 
can you show me how to send parameters to the backend side using this package?

**Comment by pr-Mais** [comment]
https://github.com/nyartech/hyperpay/blob/b0dbf0fbddc799a0bfe26dc79f7cfeca5742b3d7/example/lib/checkout_view.dart#L40-L55

**Comment by suhaibAlbdoor** [comment]
@> https://github.com/nyartech/hyperpay/blob/b0dbf0fbddc799a0bfe26dc79f7cfeca5742b3d7/example/lib/checkout_view.dart#L40-L55

**Comment by suhaibAlbdoor** [comment]
> 

@pr-Mais 
i mean where to send 
 1)entityId
 2)amount
3)payment type
4) currency
in your package code , i do not know where to add this necessary params also where to add access token

**Comment by suhaibAlbdoor** [comment]
@pr-Mais 

i mean where to send
1)entityId
2)amount
3)payment type
4) currency
in your package code , i do not know where to add this necessary params also where to add access token

**Comment by pr-Mais** [comment]
Check the example app I posted above, all additional parameters can be sent in `additionalParams`. Entity IDs are configured as part of your `HyperpayConfig` 
https://github.com/nyartech/hyperpay/blob/main/example/lib/constants.dart

The plugin currently only supports Credit Cards (Master, VISA) and MADA entities.
