### ISSUE TITLE
invalid or missing parameter

### ISSUE THREAD

**Issue by softDevos** [nyartech/hyperpay#23]
it's shows me this error message event though i parse the entity ID's

```
Uri _checkoutEndpoint = Uri(
  scheme: 'https',
  host: 'eu-test.oppwa.com',
  path: 'v1/checkouts',
  queryParameters: {
    'entityId': 'alsdkjfalskdjl923479523hkasjf',
  },
);
```

```
Uri _statusEndpoint = Uri(
  scheme: 'https',
  host: 'eu-test.oppwa.com',
  path: 'v1/payments',
  queryParameters: {
    'entityId': 'alsdkjfalskdjl923479523hkasjf',
  },
);
```

`[{"name":"entityId","value":null,"message":"invalid or missing parameter"}]}`

**Comment by softDevos** [comment]
Hello dear 
Well here I'm trying to integrate apple pay into the test mode, Then as you see on the screen below it's showing me 
that the payment is done 100%. And returned success but when I navigate to the apple dashboard I didn’t find any kind of transaction.
So do I have to go ahead with the live mode?

<img width="960" alt="Screen Shot 2022-07-21 at 8 37 43 AM" src="https://user-images.githubusercontent.com/100356839/180137715-1be1adde-5a08-4303-8e49-e2a53b11ce5b.png">

**Comment by Ashwaq3** [comment]
how did you solve it? @softDevos

**Comment by musanedh** [comment]
`
String _host = 'Host.com';

Uri _checkout = Uri(
  scheme: 'https',
  host: _host,
  path: '/api/v1/checkouts',
);

Uri _status = Uri(
  scheme: 'https',
  host: _host,
  path: '/api/v1/payments',
);`


and also the [ ** entityId ** ] like this [ entityID ]

**Comment by musanedh** [comment]
If it didn’t work with you just inform me I'm here to help
