### ISSUE TITLE
I am getting an error in invalid or missing parameter  .. I don't know how to solve the issuse .. please help me out .

### ISSUE THREAD

**Issue by Atharsaeed1** [nyartech/hyperpay#31]
400: {"result":{"code":"200.300.404","description":"invalid or missing parameter","parameterErrors":[{"name":"entityID","value":"8ac7a4c87fce1108017fd0d0925e13a9","message":"is not an allowed parameter"}]},"buildNumber":"3d38ea0e4da85195867ec12eababc8d1828ecfa2@2022-09-23 00:42:34 +0000","timestamp":"2022-09-23 13:49:20+0000","ndc":"DC4EF09F01484266B259F3C6D02CFF5E.uat01-vm-tx02"}

**Comment by pr-Mais** [comment]
This issue is not related to this plugin. Please contact HyperPay support.
