### ISSUE TITLE
Could not find :oppwa.mobile-4.5.0-release

### ISSUE THREAD

**Issue by mjidaladin** [nyartech/hyperpay#32]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :oppwa.mobile-4.5.0-release:.
     Required by:
         project :app

**Comment by pr-Mais** [comment]
Which version are you using?
