### ISSUE TITLE
Host Name

### ISSUE THREAD

**Issue by ibrahim-atif** [nyartech/hyperpay#4]
Dear eng.
I hope you are fine.
I just have small question which is String_host
Value what do mean with it as i assigned "https://test.oppwa.com/"
To it but it is false as in the run in terminal it says sting-host value is 4 hex digits.
So i need your help.
Besy regards.

**Comment by pr-Mais** [comment]
Hello, please provide a code snippet explaining which value are you referring to.

I'm assuming you mean the server host, which indicates your own host, all requests will fail until you implement the required endpoints on your server and provide it on initialization as [in the example](https://github.com/nyartech/hyperpay/blob/main/example/lib/constants.dart).

**Comment by pr-Mais** [comment]
Have you implemented your *own* endpoints on your *own* server as [shown clearly in this guide](https://wordpresshyperpay.docs.oppwa.com/tutorials/mobile-sdk/integration/server)?
The call to `test.oppwa.com` shouldn't be the host in your client app, it must happen server-to-server.

**Comment by AbdrahumanFikry** [comment]
String _host = 'test.oppwa.com';

Uri _checkoutEndpoint = Uri(
  scheme: 'https',
  host: _host,
  path: '',
);

Uri _statusEndpoint = Uri(
  scheme: 'https',
  host: _host,
  path: '',
);


  /// Initialize HyperPay session
  Future<void> initPaymentSession(
    BrandType brandType,
    double amount,
  ) async {
    CheckoutSettings _checkoutSettings = CheckoutSettings(
      brand: brandType,
      amount: amount,
      headers: {
        'Authorization':
            'Bearer $token'
      },
      additionalParams: {
        'merchantTransactionId': '#123456',
      },
    );

    hyperpay.initSession(checkoutSetting: _checkoutSettings);
    sessionCheckoutID = await hyperpay.getCheckoutID;
  }
When I did that  I got this response :

 FormatException: Unexpected character (at character 1)
 <html></html>
 ^

---------------------------------------------------------------------------------------------
Do you mean that the host name should be my own ? even on test Mode? @pr-Mais

**Comment by pr-Mais** [comment]
Yes even on test mode .You will need to set your backend either ways to accept both testing and production environments.

**Comment by AbdrahumanFikry** [comment]
Ok thanks a lot , Is this the reason why I get this response :

==> FormatException: Unexpected character (at character 1)
==> `<html></html>`
==> ^

**Comment by pr-Mais** [comment]
Most probably yes. It's not the response the plugin is expecting.

**Comment by AbdrahumanFikry** [comment]
```
String _host = 'karaj-payment.cc';

Uri _checkoutEndpoint = Uri(
  scheme: 'https',
  host: _host,
  path: '/shopper/redirect',
);

Uri _statusEndpoint = Uri(
  scheme: 'https',
  host: _host,
  path: '',
);
```
Is this Right ?
_________________
Now I am getting this error :

```
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
```

@pr-Mais
