### ISSUE TITLE
 HandshakeException: Handshake error in client (OS Error:  	WRONG_VERSION_NUMBER(tls_record.cc:242))

### ISSUE THREAD

**Issue by MohamedEalbd** [nyartech/hyperpay#6]
![hyperscreen](https://user-images.githubusercontent.com/59833489/140649346-5ddb29e4-ef5a-447f-8307-5890c92f01e9.jpg)
Dear eng.
I hope you are fine.
I just have a problem when connecting with my server and entering credit card data and press pay I find this error
 HandshakeException: Handshake error in client (OS Error:  	WRONG_VERSION_NUMBER(tls_record.cc:242))

**Comment by pr-Mais** [comment]
Did you try running your endpoint in postman?

**Comment by MohamedEalbd** [comment]
yes
![Screenshot 2021-11-07 064423](https://user-images.githubusercontent.com/59833489/140649809-151d2442-8c63-48d4-b704-29cc9c6befdd.jpg)

**Comment by MohamedEalbd** [comment]
send scheme https or http?

**Comment by pr-Mais** [comment]
Since I see in postman your endpoint has http scheme, try with it.

**Comment by MohamedEalbd** [comment]
![http](https://user-images.githubusercontent.com/59833489/140650014-7c6ff30c-dfcb-4392-a26d-4d67f6244782.jpg)
with http scheme 
HttpException: 404:

**Comment by pr-Mais** [comment]
Make sure you're sending the correct headers in `CheckoutSettings`

**Comment by MohamedEalbd** [comment]
![pos](https://user-images.githubusercontent.com/59833489/140650810-ba83ee29-c512-4e00-920c-96cb1271cf9b.jpg)
now I change get to post but still have error HttpException: 415:
![post](https://user-images.githubusercontent.com/59833489/140650835-7e8c26af-5abe-4eec-8442-533a499a0eb8.jpg)
r

**Comment by MohamedEalbd** [comment]
![setting](https://user-images.githubusercontent.com/59833489/140650942-51b17c3f-a3f7-4a36-9d93-3ab3686e51e5.jpg)
my headers in CheckoutSettings

**Comment by pr-Mais** [comment]
The key in the code is 'Authorization' and in Postman I see 'Token'.
Additionally, please add the Authorization token to your backend, it shouldn't be sent from client.

**Comment by pr-Mais** [comment]
Make sure you have the correct entityIDs in `HyperpayConfig`.

**Comment by MohamedEalbd** [comment]
actually Authorization token added in backend, this token that sending in postman and code  for our server 
and Iam sure  entityIDs is correct

**Comment by pr-Mais** [comment]
The `entityId`, `amount` and `additionalParams` are sent in the request body, in Postman I see they are still queryParameters, so I guess your backend isn't receiving the params, try in postman to remove the amount and entityId from the query and put them in body, if it give the same error 415 then that's the problem.

**Comment by MohamedEalbd** [comment]
![bbv](https://user-images.githubusercontent.com/59833489/140651523-043b8717-71f9-4381-9f0a-1a5c994c7fc0.jpg)
work

**Comment by pr-Mais** [comment]
Use breakpoints to debug if the request is being sent correctly.

**Comment by pr-Mais** [comment]
Possibly try to add `Content-Type` to headers, [read about what 415 status code means](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415).

**Comment by MohamedEalbd** [comment]
hello sir,
I hope you are fine.
Release App Not Opening After Install, icon and label not show in mobile home screen but after hash this line <data android:scheme="co.atma.QueenTasteFront.payments" />--> 
 Release App work done

**Comment by pr-Mais** [comment]
It's mentioned in the [Android Setup](https://github.com/nyartech/hyperpay#android-setup) section of README:
"IMPORTANT: the scheme you choose should match exactly your application ID but without any underscores, and then append .payments to it. 
For example: com.nyartech.hyperpay_example becomes com.nyartech.hyperpayexample.payments"

**Comment by MohamedEalbd** [comment]
I really do it my scheme match exactly my application ID but without any underscores, and then append .payments

**Comment by pr-Mais** [comment]
I don't understand, is the app working or not? 
if you have an issue provide the full details so I can help you better.

**Comment by MohamedEalbd** [comment]
not working when build release App Not Opening After Install

**Comment by pr-Mais** [comment]
Without any additional details about the error, I'm not sure if the plugin is causing it.

**Comment by MohamedEalbd** [comment]
can I pm with you in twitter ?

**Comment by pr-Mais** [comment]
I prefer you send all details here publicly so everyone having the same problem can see.

**Comment by MohamedEalbd** [comment]
Release App Not Opening After Install, icon and label not show in mobile home screen but after hash this line
data android:scheme="co.atma.QueenTasteFront.payments" in AndroidManifest
Release App work done and iam sure scheme match exactly my application ID

**Comment by pr-Mais** [comment]
Make sure the AndroidManifest matches exactly the [example app](https://github.com/nyartech/hyperpay/blob/32e4a94f6dda6b47532a5c39bd84adbcc3e8a8ed/example/android/app/src/main/AndroidManifest.xml#L18).
