### ISSUE TITLE
[Feature Request] Apple Pay Integration

### ISSUE THREAD

**Issue by shashoug** [nyartech/hyperpay#7]
Is it possible to implement ApplePay? 
My Application depends on ApplePay, and there's no documentations comes with this plugin to achieve that.

**Comment by pr-Mais** [comment]
We will try to get it implemented soon but yet no promises.
Any PRs to help are welcomed though!

**Comment by shashoug** [comment]
@pr-Mais 
I'm working now to make it with PlatformMethod, if i achieved anything near close, i will inform you with the result.

**Comment by pr-Mais** [comment]
Thank you.

**Comment by pr-Mais** [comment]
Following up on this since we have some requests, it's the next thing to be supported, but the timeline currently isn't clear as I'm pretty busy.
If anyone can help would be thankful.

**Comment by shashoug** [comment]
@pr-Mais  I think i did something with Native method channel but it's not well formed and i need some help to make it perfect, if you are interested to implement that on your library after fixing it, feel free to ping me.

**Comment by pr-Mais** [comment]
Open a PR.
